# Generated by Django 5.2.5 on 2025-09-20 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TravelInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('destination', models.CharField(max_length=255)),
                ('departure_date', models.DateField()),
                ('return_date', models.DateField()),
                ('travelers', models.PositiveIntegerField()),
                ('budget_range', models.CharField(max_length=50)),
                ('travel_type', models.CharField(max_length=100)),
            ],
        ),
    ]
